//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPortfolioProjectNigth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feature
    {
        public int Featureldid { get; set; }
        public string Title { get; set; }
        public string NameSurname { get; set; }
        public string Subtitle { get; set; }
    }
}
